apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-ms-product
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ms-product-deployment
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 90