apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-report-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-report
  template:
    metadata:
      labels:
        app: ms-report
    spec:
      containers:
        - name: ms-report
          image: 401196964700.dkr.ecr.us-east-1.amazonaws.com/ms-report:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: db-working-hours-secret
                  key: url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-working-hours-secret
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-working-hours-secret
                  key: password
              
          startupProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 15
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            failureThreshold: 1
            periodSeconds: 20