apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-employee-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-employee
  template:
    metadata:
      labels:
        app: ms-employee
    spec:
      containers:
        - name: ms-employee
          image: 401196964700.dkr.ecr.us-east-1.amazonaws.com/ms-employee:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
              
          startupProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 15
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            failureThreshold: 1
            periodSeconds: 20