apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: svc-ms-working-hours-registry
  annotations:
    konghq.com/strip-path: 'true'
spec:
  parentRefs:
  - name: kong
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /working-hours-registry/v1
    backendRefs:
    - name: svc-ms-working-hours-registry
      kind: Service
      port: 8080