apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-burger-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-burger
  template:
    metadata:
      labels:
        app: app-burger
    spec:
      containers:
        - name: app-burger
          image: 401196964700.dkr.ecr.us-east-1.amazonaws.com/burger-application:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: SPRING_PROFILES_ACTIVE
              value: "production"
              
          startupProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 15
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            failureThreshold: 1
            periodSeconds: 20