apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-ms-working-hours-registry
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ms-working-hours-registry-deployment
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 90