name: Deploy Application to Kubernetes
on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1 
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install kubectl
      uses: azure/setup-kubectl@v2.0
      with:
        version: 'v1.24.0' # default is latest stable
      id: install

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Update kube config
      run: aws eks update-kubeconfig --name prod
    
    - name: Deploy to EKS
      run: |
        kubectl apply -f k8s-deployment-burger-application.yaml
        kubectl apply -f k8s-svc-burger-application.yaml
        kubectl apply -f k8s-hpa-burger-application.yaml