name: Checkout
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  checkout:
    name: Checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 